// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  firebase: {
    projectId: 'multiplos-app',
    appId: '1:976318890561:web:3551db455ae548c443fcc0',
    storageBucket: 'multiplos-app.appspot.com',
    apiKey: 'AIzaSyAAUfFRDo_8jfDkpMD9emRt2zd_LjsVpks',
    authDomain: 'multiplos-app.firebaseapp.com',
    messagingSenderId: '976318890561',
  },
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
